### ISSUE TITLE
fitStahl producing inconsistent results?

### ISSUE THREAD

**Issue by auton1** [kbroman/xoi#5]
Hello!

First, thank you for releasing this package; I've learnt a lot from it!

I have a question about the behavior of fitStahl, and it may point to a lack of understanding on my part. The following code simulates some simple data that is intended to be representative of a human sample.

```
library(xoi)

L <- c(337.4350, 319.1850, 274.4540, 261.4500, 248.0100, 244.1290, 223.7910, 217.1090, 193.0760, 216.8090, 193.3080, 198.0270, 152.1770, 137.8770, 145.4600, 156.6140, 153.6600, 139.7430, 116.3510, 119.6960, 73.7764, 78.2206)

set.seed(5)
N <- 1
p = 0.1
nu = 10

xoloc <- c()
count <- 1
for (c in L)
{
  xoloc[[count]] <- simStahl(N, p=p, nu=nu, L = c)
  count <- count + 1
}

set.seed(5)
mle1 <- fitStahl(xoloc, chrlen=L, verbose = TRUE)
set.seed(5)
mle2 <- fitStahl(xoloc, chrlen=L, verbose = TRUE)
```

However, when I run this, the output contained in mle1 and mle2 is quite different, despite operating on exactly the same data and setting the random seed to be the same.

Is this expected behavior, pointing to an issue, or pointing to a lack of understanding on my part?

Thank you!

Adam

**Comment by kbroman** [comment]
The problem seems to be that the `xoloc` dataset is a list of lists of vectors, instead of just a list of vectors.

It seems to work if you change the first line in the loop to the following, with `[[1]]` at the end:

```r
  xoloc[[count]] <- simStahl(N, p=p, nu=nu, L = c)[[1]]
```

**Comment by auton1** [comment]
Aha - thank you! That explains that.
I was trying to handle the case where more than one sample is simulated (i.e. N > 1). I think simStahl outputs a list in that case. Is there an obvious way to input both multiple chromosomes and multiple samples into fitStahl?

**Comment by auton1** [comment]
Oh - I think I see; I just append the additional samples as if they were additional chromosomes.
